<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerSIvRHmg\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerSIvRHmg/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerSIvRHmg.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerSIvRHmg\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerSIvRHmg\App_KernelDevDebugContainer([
    'container.build_hash' => 'SIvRHmg',
    'container.build_id' => 'ebf7acc3',
    'container.build_time' => 1707434056,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerSIvRHmg');
